name: Deploy to AWS Elastic Beanstalk

# on Pull Reques to main or dev

on: push

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          check-latest: true 

      - name: Testing with pytest
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pytest