name: Unit tests

# on Pull Reques to main or dev

on: push

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

  create-envfile:
    runs-on: ubuntu-latest
    steps:
        - name: Make envfile with echo
          run: |
            echo "${{ secrets.DB_CLUSTER_DOMAIN }}" > .env
            echo "${{ secrets.DB_NAME }}" >> .env
            echo "${{ secrets.DB_USERNAME }}" >> .env
            echo "${{ secrets.DB_PASSWORD }}" >> .env
            echo "${{ secrets.JWT_ADMIN_TOKEN }}" >> .env
            echo "${{ secrets.JWT_DEV_TOKEN }}" >> .env
            echo "${{ secrets.JWT_EMPLOYEE_TOKEN }}" >> .env
            echo "${{ secrets.MAILGUN_API_URL }}" >> .env
            echo "${{ secrets.MAILGUN_API_KEY }}" >> .env
            echo "${{ secrets.MAILGUN_DOMAIN }}" >> .env
            echo "${{ secrets.MAILGUN_FROM }}" >> .env
            echo "${{ secrets.stage }}" >> .env

  check-envfile:
    runs-on: ubuntu-latest
    needs:  [create-envfile]
    steps:
      - name: Check all content with ls
        run: ls -a
      
  testing:
    runs-on: ubuntu-latest
    needs:  [create-envfile]
    timeout-minutes: 10
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt          

      - name: Test with pytest
        run: pytest